### PR TITLE
Update UI

### PR DESCRIPTION
**Pull request by zjesko**
## What it solves
Resolves #

### CODE REVIEW

**Comment by zjesko** [comment]
image

Turn these into black

**Comment by zjesko** [comment]
image

Fix the extra boxes and font colours

**Comment by zjesko** [comment]
use this background

**Comment by gvirus21** [comment]
> image
> 
> Turn these into black

This is WIP, i am still finding it's source

**Comment by 0xtemujin** [comment]
image
Please fix the background on this modal

**Comment by 0xtemujin** [comment]
In the Review section the name of the wallet is not visible
image
=>
image

**Comment by 0xtemujin** [comment]
Make this icon green: 
image

**Comment by 0xtemujin** [comment]
Except the first step, every other step is not visible
image

**Comment by 0xtemujin** [comment]
Safe Created! modal is still white 
image

**Comment by 0xtemujin** [comment]
Tooltip modal change to green/black color scheme for both "Copy" and "View on Explorer"
image

**Comment by 0xtemujin** [comment]
Text unreadable on this modal 
image

**Comment by 0xtemujin** [comment]
We've removed all safe apps right? @akshatcx . We can remove this option as well if so 
image

**Comment by 0xtemujin** [comment]
Change font color for readablity and change grey lines to some shade of green 
image

**Comment by 0xtemujin** [comment]
Is this USD filter required? 
image
I dont see USD prices anywhere

**Comment by 0xtemujin** [comment]
image

- Arrow and divider should have green coloring
- Balance not readable

**Comment by 0xtemujin** [comment]
image
Select asset dropdown coloring needs to be fixed

**Comment by zjesko** [comment]
image
Fix button colors

**Comment by gvirus21** [comment]
> We've removed all safe apps right? @akshatcx . We can remove this option as well if so image

Done

**Comment by gvirus21** [comment]
> Text unreadable on this modal image

Done

**Comment by gvirus21** [comment]
> Safe Created! modal is still white image

This is also a gnosis-safe module

**Comment by gvirus21** [comment]
> image
> 
> * Arrow and divider should have green coloring
> * Balance not readable

done

**Pull request merged**
